#!/bin/bash

rm run/respawn-gardens.pid
ps aux | grep CardBoxServer | grep hextilla | awk '{print $2}' | xargs kill -QUIT
ps aux | grep CardBoxServer | grep hextilla | awk '{print $2}' | xargs kill -KILL

rm run/respawn-gardens.pid
